hidl: fingerprint: Add blank callbacks for udfps
* Without this, build will throw this:

device/xiaomi/sm6150-common/fingerprint/BiometricsFingerprint.cpp:282:25: error: allocating an object of abstract class type 'android::hardware::biometrics::fingerprint::V2_3::implementation::BiometricsFingerprint'
        sInstance = new BiometricsFingerprint();
                        ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hardware/biometrics/fingerprint/2.3/IBiometricsFingerprint.h:214:47: note: unimplemented p
ure virtual method 'onShowUdfpsOverlay' in 'BiometricsFingerprint'
    virtual ::android::hardware::Return<void> onShowUdfpsOverlay() = 0;
                                              ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hardware/biometrics/fingerprint/2.3/IBiometricsFingerprint.h:219:47: note: unimplemented p
ure virtual method 'onHideUdfpsOverlay' in 'BiometricsFingerprint'
    virtual ::android::hardware::Return<void> onHideUdfpsOverlay() = 0;
                                              ^
since we don't use it, for now let's just satisfy it with blank callbacks.

Signed-off-by: azrim <mirzaspc@gmail.com>

Former-commit-id: 3d920b522f8ad170a9433419813dd85a4176ec37
Signed-off-by: Manikantaraavi <raavimanikanta6595@gmail.com>
Signed-off-by: dhanireddygovardhanreddy <dhanireddygovardhanreddy@gmail.com>